<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_model extends CI_Model
{

    public $table = 'barang';
    public $id = 'IdBarang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('IdBarang', $q);
	$this->db->or_like('NamaBarang', $q);
	$this->db->or_like('Stok', $q);
	$this->db->or_like('KetTempat', $q);
	$this->db->or_like('KetKondisi', $q);
    $this->db->or_like('KetPemilik', $q);
	$this->db->or_like('TanggalMasuk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('IdBarang', $q);
	$this->db->or_like('NamaBarang', $q);
	$this->db->or_like('Stok', $q);
	$this->db->or_like('KetTempat', $q);
	$this->db->or_like('KetKondisi', $q);
    $this->db->or_like('KetPemilik', $q);
	$this->db->or_like('TanggalMasuk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function move($id, $data)
    {
        // $data = array('Stok' => '(Stok-'$Stok')');
        $this->db->where($this->id, $id);
        // $this->db->set('Stok','Stok-".$Stok"', FALSE);
        $this->db->update($this->table, $data);
       //$this->db->query("UPDATE barang SET Stok = Stok - '.$NEW.Stok' WHERE IdBarang = '.$IdBarang'");
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    //  function dd_tempat()
    // {
    //     // ambil data dari db
    //     $this->db->order_by('tempat', 'asc');
    //     $result = $this->db->get('tempat');
        
    //     // bikin array
    //     // please select berikut ini merupakan tambahan saja agar saat pertama
    //     // diload akan ditampilkan text please select.
    //     $dd[''] = 'Please Select';
    //     if ($result->num_rows() > 0) {
    //         foreach ($result->result() as $row) {
    //         // tentukan value (sebelah kiri) dan labelnya (sebelah kanan)
    //             $dd[$row->id_tempat] = $row->tempat;
    //         }
    //     }
    //     return $dd;
    // }

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */