<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_t extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $barang = $this->Barang_model->get_all();

        $data = array(
            'barang_data' => $barang
        );

        $this->template->load('templatepp','barang_list_t', $data);
    }

    public function read($id) 
    {
        $row = $this->Barang_model->get_by_id($id);
        if ($row) {
            $data = array(
		'IdBarang' => $row->IdBarang,
		'NamaBarang' => $row->NamaBarang,
		'Stok' => $row->Stok,
		'KetTempat' => $row->KetTempat,
		'KetKondisi' => $row->KetKondisi,
        'KetPemilik' => $row->KetPemilik,
		'TanggalMasuk' => $row->TanggalMasuk,
	    );
            $this->template->load('templatepp','barang_read_t', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('barang_t'));
        }
    }

    public function create() 
    {
        
        $data = array(
            'button' => 'Create',
            'action' => site_url('barang_t/create_action'),
            // 'dd_tempat' => $this->Barang_model->dd_tempat(),
            // 'tempat_selected' => $this->input->post('tempat') ? $this->input->post('tempat') : '',
	    'IdBarang' => set_value('IdBarang'),
	    'NamaBarang' => set_value('NamaBarang'),
	    'Stok' => set_value('Stok'),
	    'KetTempat' => set_value('KetTempat'),
	    'KetKondisi' => set_value('KetKondisi'),
        'KetPemilik' => set_value('KetPemilik'),
	    'TanggalMasuk' => set_value('TanggalMasuk'),
	);
        $this->template->load('templatepp','barang_form_t', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
        'IdBarang' => $this->input->post('IdBarang',TRUE),
		'NamaBarang' => $this->input->post('NamaBarang',TRUE),
		'Stok' => $this->input->post('Stok',TRUE),
		'KetTempat' => $this->input->post('KetTempat',TRUE),
		'KetKondisi' => $this->input->post('KetKondisi',TRUE),
        'KetPemilik' => $this->input->post('KetPemilik',TRUE),
		'TanggalMasuk' => $this->input->post('TanggalMasuk',TRUE),
	    );

            $this->Barang_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('barang_t'));
        }
    }
    
   

   

    public function _rules() 
    {
	$this->form_validation->set_rules('NamaBarang', 'nama barang', 'trim|required');
	$this->form_validation->set_rules('Stok', 'stok', 'trim|required');
	$this->form_validation->set_rules('KetTempat', 'ket tempat', 'trim|required');
	$this->form_validation->set_rules('KetKondisi', 'ket kondisi', 'trim|required');
    $this->form_validation->set_rules('KetPemilik', 'ket pemilik', 'trim|required');
	$this->form_validation->set_rules('TanggalMasuk', 'tanggal masuk', 'trim|required');

	$this->form_validation->set_rules('IdBarang', 'IdBarang', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

   
}

/* End of file Buku.php */
/* Location: ./application/controllers/Buku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */