<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pelaporan extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pelaporan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $pelaporan = $this->Pelaporan_model->get_all();

        $data = array(
            'pelaporan_data' => $pelaporan
        );

        $this->template->load('template','pelaporan_list', $data);
    }


    public function _rules() 
    {
	$this->form_validation->set_rules('NamaBarang', 'nama barang', 'trim|required');
	$this->form_validation->set_rules('Stok', 'stok', 'trim|required');
	$this->form_validation->set_rules('KetTempat', 'ket tempat', 'trim|required');
	$this->form_validation->set_rules('KetKondisi', 'ket kondisi', 'trim|required');
    $this->form_validation->set_rules('KetPemilik', 'ket pemilik', 'trim|required');
	$this->form_validation->set_rules('TanggalMasuk', 'tanggal masuk', 'trim|required');

	$this->form_validation->set_rules('IdBarang', 'IdBarang', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "barang.xls";
        $judul = "barang";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	xlsWriteLabel($tablehead, $kolomhead++, "NamaBarang");
	xlsWriteLabel($tablehead, $kolomhead++, "Stok");
	xlsWriteLabel($tablehead, $kolomhead++, "KetTempat");
	xlsWriteLabel($tablehead, $kolomhead++, "KetKondisi");
    xlsWriteLabel($tablehead, $kolomhead++, "KetPemilik");
	xlsWriteLabel($tablehead, $kolomhead++, "TanggalMasuk");

	foreach ($this->Barang_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->Namabarang);
	    xlsWriteLabel($tablebody, $kolombody++, $data->Stok);
	    xlsWriteLabel($tablebody, $kolombody++, $data->KetTempat);
	    xlsWriteLabel($tablebody, $kolombody++, $data->KetKondisi);
        xlsWriteLabel($tablebody, $kolombody++, $data->KetPemilik);
	    xlsWriteNumber($tablebody, $kolombody++, $data->TanggalMasuk);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=barang.doc");

        $data = array(
            'barang_data' => $this->Barang_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('barang_doc',$data);
    }

     public function wordd()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=barang.doc");

        $data = array(
            'tanah_data' => $this->Tanah_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('tanah_doc',$data);
    }

}

/* End of file Buku.php */
/* Location: ./application/controllers/Buku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */